// 1. Création des noeuds (Aéroports)
CREATE (p:Aeroport {id: 1, nom: 'Charles de Gaulle', ville: 'Paris', pays: 'FR'})
CREATE (r:Aeroport {id: 2, nom: 'Antonio Carlos Jobim', ville: 'Rio', pays: 'BR'})
CREATE (l:Aeroport {id: 3, nom: 'Heathrow', ville: 'Londres', pays: 'GB'})
CREATE (ny:Aeroport {id: 4, nom: 'JFK', ville: 'New York', pays: 'US'})
CREATE (t:Aeroport {id: 5, nom: 'Narita', ville: 'Tokyo', pays: 'JP'})
CREATE (s:Aeroport {id: 6, nom: 'Kingsford Smith', ville: 'Sydney', pays: 'AU'})
CREATE (a:Aeroport {id: 7, nom: 'Auckland Airport', ville: 'Auckland', pays: 'NZ'})
CREATE (b:Aeroport {id: 8, nom: 'Brandenburg', ville: 'Berlin', pays: 'DE'})
CREATE (ro:Aeroport {id: 9, nom: 'Fiumicino', ville: 'Rome', pays: 'IT'})

// 2. Création des relations (Vols directs)
CREATE (p)-[:VOL_VERS {compagnie: 'Air France', num_vol: 442}]->(r)
CREATE (p)-[:VOL_VERS {compagnie: 'British Airways', num_vol: 101}]->(l)
CREATE (l)-[:VOL_VERS {compagnie: 'Virgin Atlantic', num_vol: 202}]->(ny)
CREATE (ny)-[:VOL_VERS {compagnie: 'JAL', num_vol: 303}]->(t)
CREATE (t)-[:VOL_VERS {compagnie: 'Qantas', num_vol: 404}]->(s)
CREATE (s)-[:VOL_VERS {compagnie: 'Air New Zealand', num_vol: 505}]->(a)
CREATE (b)-[:VOL_VERS {compagnie: 'Lufthansa', num_vol: 606}]->(ro);